# Generated by Django 6.0.2 on 2026-03-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
    ]
