# Generated by Django 6.0.2 on 2026-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("service", models.CharField(max_length=100)),
                ("experience", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="professionals/"
                    ),
                ),
            ],
        ),
    ]
