# Generated by Django 6.0.2 on 2026-04-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_professional"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.category",
            ),
        ),
    ]
