# Generated by Django 6.0.2 on 2026-04-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_professional_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professional",
            old_name="profile_image",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="email",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="experience",
        ),
        migrations.AddField(
            model_name="professional",
            name="availability",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="professional",
            name="location",
            field=models.CharField(default="Udupi", max_length=100),
        ),
        migrations.AddField(
            model_name="professional",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name="professional",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.category"
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="price",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8),
        ),
    ]
