# Generated by Django 6.0.2 on 2026-04-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_alter_professional_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.category",
            ),
            preserve_default=False,
        ),
    ]
