# Generated by Django 6.0.2 on 2026-04-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_alter_professional_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="professional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.professional",
            ),
        ),
    ]
