# Generated by Django 6.0.2 on 2026-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=10)),
                ("professional", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
